### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'python36' or one of its dependencies

### ISSUE THREAD

**Issue by elvinest** [SciSharp/Keras.NET#38]
I am trying to use keras.net in .net core webapp, I have installed python 3.6.8 ( not using virtual environment), numpy 1.16.3, tensorflow 1.14.0 (including keras). 

![QQ截图20190925153413](https://user-images.githubusercontent.com/3347361/65579450-567d5700-dfaa-11e9-8041-b782512c06c9.jpg)

I try to set python 3.6 path, but can't work.
Python.Runtime.PythonEngine.PythonPath = @"E:\Python\Python36";

How should I do it? Help me please! Thanks.

**Comment by deepakkumar1984** [comment]
There was a similar issue which I have an example https://github.com/SciSharp/Keras.NET/issues/7

Could you please check it?

**Comment by elvinest** [comment]
Thank you for replying, I have checked it, but i think this is two different questions.

**Comment by elvinest** [comment]
Running Python library has gone wrong，e.g:

Python.Runtime.PythonEngine.Initialize();

not yet running to the keras section

**Comment by deepakkumar1984** [comment]
The function is called internally, you don't have to invoke it. Can you share me your project to debug?

**Comment by solarflarefx** [comment]
I seem to be having the same problem. 

I have the following installed:
Python 3.6.1 (64-bit)
Numpy 1.17.2
Keras 2.2.4
Tensorflow 1.14.0

If I run Python via command line I have no problems.  But if I try to run the BasicSamples program, then I get "System.DllNotFoundException: 'Unable to load DLL 'python36' or one of its dependencies: The specified module could not be found. "

The error happens when trying to execute the following line:
NDarray x = np.array(new float[,] { { 0, 0 }, { 0, 1 }, { 1, 0 }, { 1, 1 } });

It seems that this Visual Studio project doesn't seem to recognize my Python installation, though Visual Studio seems to see Python if I go to: View --> Other Windows --> Python Environments

I am simply trying to run the example, so I must be doing something wrong here.  Is there some prerequisite package I am missing?  Does it have to do with my project settings?  Does it have to do with versions of Python libraries?

**Comment by deepakkumar1984** [comment]
Are you using virtual environment?

**Comment by deepakkumar1984** [comment]
Does it work from command line
> Python
import numpy
numpy.version.version

**Comment by solarflarefx** [comment]
I tried both a virtual environment and a custom environment that links to my local Python build.  I am using Windows 10 64-bit with VS 2019. 

Python does work by command line.

numpy.version.version returns: 1.17.2

**Comment by deepakkumar1984** [comment]
Can you upgrade your numpy, keras and tensorflow

**Comment by deepakkumar1984** [comment]
This should be something related to VS not picking up python, could you run the following and check whats being logged

![image](https://user-images.githubusercontent.com/6328361/66264788-5b1bf800-e853-11e9-8adc-4335cf72d8d6.png)

And should be similar to 
![image](https://user-images.githubusercontent.com/6328361/66264800-99191c00-e853-11e9-8168-ddac1565b0be.png)

**Comment by solarflarefx** [comment]
Where are you typing the first window?

My windows command line output looks similar.

**Comment by deepakkumar1984** [comment]
The first window is code in VS console project. Just to check what python path are loaded

**Comment by solarflarefx** [comment]
Sorry I'm a bit confused.  How do I get to the first window?  Are you suggesting I create a new console project and run the code displayed in your first image?

**Comment by solarflarefx** [comment]
Well, a Python36 Interactive windows does appear in VS:

![Capture](https://user-images.githubusercontent.com/45402633/67100909-93460380-f18e-11e9-8c0f-20083dd435ce.PNG)

But when I try to run the example, I get this error:
![Capture2](https://user-images.githubusercontent.com/45402633/67101039-e455f780-f18e-11e9-839c-0eaf8987c491.PNG)

Here is my attempt to write the code you had said into VS:
![Capture3](https://user-images.githubusercontent.com/45402633/67101664-0ef48000-f190-11e9-91de-a93032a31aa0.PNG)

**Comment by deepakkumar1984** [comment]
Its an system issue with VS not finding python. There is nothing we can do with keras code, so closing the issue
