### ISSUE TITLE
No module named 'encodings'

### ISSUE THREAD

**Issue by GhostUnion** [SciSharp/Keras.NET#69]
keras
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

someone say not support anaconda env,really?

**Comment by deepakkumar1984** [comment]
Can you try with standard python?

**Comment by deepakkumar1984** [comment]
Can you check this thread:
https://stackoverflow.com/questions/38132755/importerror-no-module-named-encodings

Seems like python installation issue.

**Comment by Nodice** [comment]
I had to do a lot to resolve this issue. The issue source is due to a corrupted Python and/or Anaconda3 install on a windows 10 machine. There are also issues with the Security level on Install.

To resolve the issue:
Uninstall Anaconda3:
Uninstall All versions of Python if more are installed:
Download the Anaconda3 Installer, Right click on it and "Run as Administrator"
Install Anaconda3 for all users. This will place it in C:\ProgramData\Anaconda3 by default. Python 3.7 is installed with Anaconda3 as of this date.
Install Pip
Install Tensorflow 1.15 (CPU and GPU are both in the install now) (PIP Install Tensorflow==1.15)
Install Keras (Pip Install Keras)
Install Cuda Toolkit if you want to run the GPU version. Download Cuda 10.0, right click on the exe and "Run as administrator" v10.1 and v10.2 do not work with Tensorflow 1.15 as of this date.
Open a CMD prompt using "Run as Administrator". Verify that python works and throws no errors. If it throws errors, read them and try and resolve the errors. 
If Python is working, try and load Tensorflow in python. "Import Tensorflow as TF" If it throws errors read and resolve the errors. (Mine complained about cuda issues, resolved with removal and reinstall of 10.0)
Download the entire Keras Project and Compile in VS 2019. Run the ImageExamples sample. It should throw open a window and train the model. If it does not verify your enviroment Path, PythonHome and Cuda_Path.

**Comment by niskov** [comment]
Were you able to workaround that issue? I noticed something very interesting - when debugging my app - I get the above message, but running it directly (by calling the executable file) - it works perfect. I tried monitoring the app using procmon, but couldn't find anything.

**Comment by sam0458** [comment]
I built the keras.net app and ran it directly as exe file without problem on the computer with installed python3.7. Then I copied the release directory to another computer  and added python.dll and python37.dll. That  computer did not have python 3.7 installed.  When I ran exe file I got 
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

I am wondering how  to use keras.net based C#  exe or embedded dll  application on computer that does not have python installed?
