### ISSUE TITLE
Still cannot work in WPF or WinForms with .NET Core 3.0

### ISSUE THREAD

**Issue by Robotxm** [SciSharp/Keras.NET#73]
Few months ago I reported #43.
It seems that Keras.NET still cannot work in WPF or WinForms with .NET Core 3.0?
Strangely it works in Consonle App with .NET Core 3...

**Comment by deepakkumar1984** [comment]
Fixed with latest code. 

Use Keras.Keras.DisablePySysConsoleLog = true;

Some of the python module uses sys.strerr and sys.stdout which doesn't work for windows form cause console is missing. The "DisablePySysConsoleLog" will disable logging to console.

You can get the console logs by invoking

string stdout = Keras.Keras.GetStdOut();

string stderr = Keras.Keras.GetStdError();

![image](https://user-images.githubusercontent.com/6328361/71541192-237da180-29a5-11ea-9f8f-549e6824a7ed.png)

**Comment by deepakkumar1984** [comment]
Example: https://github.com/SciSharp/Keras.NET/tree/master/Examples/WindowFormEx
